#!/bin/bash

# ---------------------------#
# 	TomaSh env var	         #
# ---------------------------#

#####################
#   MONGO           #
#####################
#export PATH=/path/to/Mongo/bin/folder

#####################
#	SET BASH COLOR	#
#####################
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

#############
#	JAVA	#
#############
#export JAVA_HOME=/path/to/jdk folder
#export PATH=$PATH:$JAVA_HOME/bin

#############
#	MAVEN	#
#############
#export M2_HOME=/path/to/maven
#export PATH=$PATH:$M2_HOME/bin


#############
#	GIT		#
#############
#export GIT_HOME=/patk/to/git
#export PATH=$PATH:$GIT_HOME/bin
